Minimize diff

diff --git a/build/mac/hyper b/build/mac/hyper
--- a/build/mac/hyper
+++ b/build/mac/hyper
@@ -1,27 +1,26 @@
 #!/usr/bin/env bash
+# Deeply inspired by https://github.com/Microsoft/vscode/blob/1.65.2/resources/darwin/bin/code.sh
 
 # TODO: bash is deprecated on macOS and will be removed.
 # Port this to /bin/sh or /bin/zsh
 
-# Adapted from Microsoft Visual Studio Code:
-# https://github.com/Microsoft/vscode/blob/1.65.2/resources/darwin/bin/code.sh
-
 function app_realpath() {
-	SOURCE=$1
-	while [ -h "$SOURCE" ]; do
-		DIR=$(dirname "$SOURCE")
-		SOURCE=$(readlink "$SOURCE")
-		[[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
-	done
-	SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
-	echo "${SOURCE_DIR%%"${SOURCE_DIR#*.app}"}"
+  SOURCE=$1
+  while [ -h "$SOURCE" ]; do
+    DIR=$(dirname "$SOURCE")
+    SOURCE=$(readlink "$SOURCE")
+    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
+  done
+  SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
+  echo "${SOURCE_DIR%%"${SOURCE_DIR#*.app}"}"
 }
 
 APP_PATH="$(app_realpath "${BASH_SOURCE[0]}")"
 if [ -z "$APP_PATH" ]; then
-	echo "Unable to determine app path from symlink : ${BASH_SOURCE[0]}"
-	exit 1
+  echo "Unable to determine app path from symlink : ${BASH_SOURCE[0]}"
+  exit 1
 fi
+
 CONTENTS="$APP_PATH/Contents"
 ELECTRON="$CONTENTS/MacOS/Hyper"
 CLI="$CONTENTS/Resources/bin/cli.js"
